/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppH2: typeof import('./../components/AppH2.vue')['default']
    AppPre: typeof import('./../components/AppPre.vue')['default']
    AppRoundedBorder: typeof import('./../components/AppRoundedBorder.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleTimer: typeof import('./../components/SimpleTimer.vue')['default']
    Timer: typeof import('./../components/Timer.vue')['default']
  }
}
